services:
  - type: web
    name: ai-media-threat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
